import React, { useState } from 'react';
import { FileSpreadsheet, Download, Printer, ShieldCheck, CheckCircle2, AlertTriangle, FileText, Share2, MoreVertical, Eye } from 'lucide-react';
import { WorkflowReport } from '../types';

interface ReportsPageProps {
  report?: WorkflowReport | null;
  onExecuteDiagnostic: () => void;
}

export const ReportsPage: React.FC<ReportsPageProps> = ({ report, onExecuteDiagnostic }) => {
  const [selectedReportId, setSelectedReportId] = useState('rep-1');

  const reportList = [
    {
      id: 'rep-1',
      name: 'FY2026 Q2-Q3 Executive Diagnostic & Strategy Brief',
      type: 'Executive Intelligence',
      created: 'Today, 10:15 AM',
      status: 'Verified',
      generatedBy: 'Supervisor & Multi-Agent Fleet',
      format: 'PDF / Excel'
    },
    {
      id: 'rep-2',
      name: 'September Margin Contraction Root-Cause Audit',
      type: 'Financial Forensic',
      created: 'Oct 3, 2026',
      status: 'Verified',
      generatedBy: 'BI & Anomaly Detection Agents',
      format: 'PDF / CSV'
    },
    {
      id: 'rep-3',
      name: 'Q4 2026 Predictive Sales & Revenue Forecast',
      type: 'ML Forecast',
      created: 'Oct 1, 2026',
      status: 'Verified',
      generatedBy: 'Forecasting Agent (Ensemble ML)',
      format: 'PDF / Excel'
    },
    {
      id: 'rep-4',
      name: 'Enterprise Customer Retention & Churn Risk Dossier',
      type: 'Customer Analytics',
      created: 'Sep 28, 2026',
      status: 'Verified',
      generatedBy: 'Customer Segmentation Agent',
      format: 'PDF / CSV'
    }
  ];

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadCSV = () => {
    const csvContent =
      "Metric,Value\n" +
      "6-Month Revenue,$1026000\n" +
      "6-Month Net Profit,$311870\n" +
      "August Revenue,$195000\n" +
      "September Revenue,$178000\n" +
      "September Profit,$42720\n" +
      "October ML Forecast,$192500\n" +
      "Problem Product 1,Enterprise Pro X1 (SKU-PRO-X1)\n" +
      "Problem Product 2,Ultra-High-Speed Fiber Interface Kit (SKU-ACC-09)\n";

    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `AgentBI_Executive_Report_${Date.now()}.csv`;
    a.click();
  };

  return (
    <div className="space-y-6 pb-8">
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="inline-flex items-center gap-1.5 text-xs font-semibold text-blue-600 bg-blue-50 px-2.5 py-1 rounded-md mb-1.5">
            <FileSpreadsheet className="w-3.5 h-3.5" />
            <span>Autonomous Intelligence Reporting</span>
          </div>
          <h1 className="text-xl sm:text-2xl font-bold text-slate-900 tracking-tight">
            Reports
          </h1>
          <p className="text-xs sm:text-[13px] text-slate-500 mt-0.5">
            Audit-ready executive briefings generated by autonomous agent workflows.
          </p>
        </div>

        <div className="flex items-center gap-2.5">
          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 px-3.5 py-2 rounded-lg bg-white hover:bg-slate-50 border border-slate-200 text-xs font-semibold text-slate-700 shadow-2xs transition"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Download PDF</span>
          </button>

          <button
            onClick={handleDownloadCSV}
            className="flex items-center gap-1.5 px-3.5 py-2 rounded-lg bg-blue-600 hover:bg-blue-700 text-white text-xs font-semibold shadow-xs transition"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Export CSV</span>
          </button>
        </div>
      </div>

      {/* Reports Table (Matches Section 26: Report Name, Type, Created, Status, Generated By, Actions) */}
      <div className="bg-white rounded-xl border border-slate-200/90 shadow-2xs overflow-hidden">
        <div className="px-5 py-4 border-b border-slate-100 flex items-center justify-between">
          <h3 className="text-[14px] font-bold text-slate-900">Executive Report Repositories</h3>
          <span className="text-xs text-slate-400">{reportList.length} reports published</span>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="bg-slate-50 text-slate-500 uppercase text-[10px] font-semibold border-b border-slate-200">
              <tr>
                <th className="py-2.5 px-4">Report Name</th>
                <th className="py-2.5 px-4">Type</th>
                <th className="py-2.5 px-4">Created</th>
                <th className="py-2.5 px-4">Status</th>
                <th className="py-2.5 px-4">Generated By</th>
                <th className="py-2.5 px-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 text-slate-700">
              {reportList.map((r) => (
                <tr key={r.id} className="hover:bg-slate-50/60 transition">
                  <td className="py-3.5 px-4">
                    <div className="flex items-center gap-2.5">
                      <div className="w-7 h-7 rounded-lg bg-blue-50 text-blue-600 flex items-center justify-center shrink-0">
                        <FileText className="w-3.5 h-3.5" />
                      </div>
                      <span className="font-semibold text-slate-900">{r.name}</span>
                    </div>
                  </td>
                  <td className="py-3.5 px-4 text-slate-600 font-medium">
                    {r.type}
                  </td>
                  <td className="py-3.5 px-4 text-slate-500 font-mono">
                    {r.created}
                  </td>
                  <td className="py-3.5 px-4">
                    <span className="inline-flex items-center gap-1 text-[10.5px] font-semibold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded-full border border-emerald-200">
                      <ShieldCheck className="w-3 h-3 text-emerald-600" />
                      <span>{r.status}</span>
                    </span>
                  </td>
                  <td className="py-3.5 px-4 text-slate-600 text-[11.5px]">
                    {r.generatedBy}
                  </td>
                  <td className="py-3.5 px-4 text-right">
                    <div className="flex items-center justify-end gap-2">
                      <button
                        onClick={handlePrint}
                        className="text-xs font-semibold text-blue-600 hover:text-blue-700 transition"
                      >
                        View
                      </button>
                      <span className="text-slate-300">·</span>
                      <button
                        onClick={handleDownloadCSV}
                        className="text-xs font-semibold text-slate-600 hover:text-slate-900 transition"
                      >
                        Export
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Document View Card */}
      <div className="bg-white rounded-xl border border-slate-200/90 p-6 sm:p-8 shadow-2xs space-y-6">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-4 border-b border-slate-100">
          <div>
            <h2 className="text-base sm:text-lg font-bold text-slate-900">
              {report?.title || 'Executive Business Intelligence & Diagnostic Report (FY2026 Q2-Q3)'}
            </h2>
            <div className="text-xs text-slate-500 mt-0.5">
              Verified by Fact Checker Agent • Target Horizon: Last 6 Months (April - September 2026)
            </div>
          </div>
          <span className="text-xs font-semibold px-2.5 py-1 rounded bg-emerald-50 text-emerald-700 border border-emerald-200 flex items-center gap-1 self-start sm:self-auto">
            <CheckCircle2 className="w-3.5 h-3.5" />
            <span>Audit-Verified against Primary Ledger</span>
          </span>
        </div>

        {/* Executive Summary Section */}
        <div className="p-4 rounded-xl bg-slate-50/70 border border-slate-200/80 space-y-1.5">
          <h3 className="text-xs font-bold text-blue-600 uppercase tracking-wider">
            1. Executive Synthesis
          </h3>
          <p className="text-xs sm:text-[13px] text-slate-700 leading-relaxed font-normal">
            {report?.executiveSummary ||
              "Top-line sales climbed consistently from April through August (reaching $195,000). In September, revenue contracted by -8.7% ($178,000) while net profit plummeted by -29.3% ($42,720 vs $60,450). Diagnostic decomposition isolates 'Enterprise Pro X1' (SKU-PRO-X1) and 'Fiber Interface Kit' as the root drivers, suffering 10.5% and 18.5% margin erosion due to temporary spot-market component price surges and promotional coupon stacking. Our ML model projects an October rebound to $192,500 within a 95% confidence interval of [$181,000, $204,000]."}
          </p>
        </div>

        {/* KPI Scorecard */}
        <div className="space-y-3">
          <h3 className="text-xs font-bold text-slate-500 uppercase tracking-wider">
            2. Verified KPI Scorecard
          </h3>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            <div className="p-3.5 rounded-lg bg-white border border-slate-200">
              <div className="text-[11px] text-slate-500">Total 6-Month Sales</div>
              <div className="text-base font-bold text-slate-900 mt-1">$1,026,000</div>
            </div>
            <div className="p-3.5 rounded-lg bg-white border border-slate-200">
              <div className="text-[11px] text-slate-500">Total 6-Month Profit</div>
              <div className="text-base font-bold text-emerald-600 mt-1">$311,870</div>
            </div>
            <div className="p-3.5 rounded-lg bg-white border border-slate-200">
              <div className="text-[11px] text-slate-500">September Margin Drop</div>
              <div className="text-base font-bold text-rose-600 mt-1">31.0% &rarr; 24.0%</div>
            </div>
            <div className="p-3.5 rounded-lg bg-white border border-slate-200">
              <div className="text-[11px] text-slate-500">October ML Projection</div>
              <div className="text-base font-bold text-blue-600 mt-1">$192,500 (+8.1%)</div>
            </div>
          </div>
        </div>

        {/* Strategic Roadmap */}
        <div className="space-y-3">
          <h3 className="text-xs font-bold text-slate-500 uppercase tracking-wider">
            3. Prioritized Strategic Roadmap
          </h3>
          <div className="space-y-2">
            {[
              { priority: 'Immediate', action: 'Disable coupon stacking on wholesale accessory tiers to immediately reclaim $3.4k/mo.' },
              { priority: 'High', action: 'Lock in 90-day forward component hedging contracts for SKU-PRO-X1 hardware.' },
              { priority: 'Medium', action: 'Re-align sales incentives toward high-margin AI Studio Enterprise Seat SaaS licenses (75.3% margin).' }
            ].map((rec, i) => (
              <div key={i} className="p-3.5 rounded-lg bg-slate-50 border border-slate-200 flex items-center justify-between text-xs">
                <div className="flex items-center gap-2.5">
                  <span className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase ${
                    rec.priority === 'Immediate' ? 'bg-rose-100 text-rose-700' : 'bg-blue-100 text-blue-700'
                  }`}>
                    {rec.priority}
                  </span>
                  <span className="text-slate-800 font-medium">{rec.action}</span>
                </div>
                <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};
